#clear out **absolutely everything**...
#docker system prune -a -f --volumes

#https://docs.docker.com/compose/compose-file/
version: '3.8'

services:
  producerapp:
    container_name: producerapp
    build:
      context: .
      dockerfile: src/ProducerApp/Dockerfile
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq

  consumerapp:
    container_name: consumerapp
    build:
      context: .
      dockerfile: src/ConsumerApp/Dockerfile
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
  
  rabbitmq:
    image: rabbitmq:3-management #-alpine
    #image: rabbitmq:management
    container_name: rabbitmq
    ports:
    - 5672:5672
    - 15672:15672
    volumes:
    #- ./.docker/rabbitmq/etc/:/etc/rabbitmq/
    - /c/temp/_DockerCompose/rabbitmq/etc/:/etc/rabbitmq/
    #- /c/temp/_DockerCompose/rabbitmq/data/:/var/lib/rabbitmq/
    - /c/temp/_DockerCompose/rabbitmq/data/:/var/lib/rabbitmq/mnesia/ #https://github.com/docker-library/rabbitmq/issues/171#issuecomment-316302131
    - /c/temp/_DockerCompose/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
    #- RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
    - RABBITMQ_ERLANG_COOKIE='mysecret'
    - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-admin}
    - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-admin}
    #docker exec rabbitmq rabbitmq-plugins enable rabbitmq_management

  # rabbitmq2:
  #   image: rabbitmq
  #   links:
  #     - rabbitmq1
  #   environment:
  #     - CLUSTERED=true
  #     - CLUSTER_WITH=rabbitmq1
  #     - RAM_NODE=true
  #   ports:
  #     - "5673:5672"
  #     - "15673:15672"

  # rabbitmq3:
  #   image: rabbitmq
  #   links:
  #     - rabbitmq1
  #     - rabbitmq2
  #   environment:
  #     - CLUSTERED=true
  #     - CLUSTER_WITH=rabbitmq1
  #   ports:
  #     - "5674:5672"

  #jaegertracing/all-in-one   https://www.jaegertracing.io/docs/1.21/getting-started/
  #openzipkin/zipkin          https://github.com/openzipkin-attic/docker-zipkin/blob/master/docker-compose.yml